### ISSUE TITLE
AX3000t - SyntaxError: unmatched ')'

### ISSUE THREAD

**Issue by Serge319** [openwrt-xiaomi/xmir-patcher#35]
Hi. I've tried to get openwrt on AX3000t. Then I got this message , after I had connected to device - 
Traceback (most recent call last):
  File "connect.py", line 56, in <module>
    import connect6
  File "E:\AX3000t\xmir-patcher-main\connect6.py", line 108
    for exp_func in exp_list):
                            ^
SyntaxError: unmatched ')'

Then I saw U had modified this two files (connect and connect6) only 4 ours earlier. I think there maybe some issue in this updates. please check it as soon as possible. There hadn't been such problem with this router before this updates. Thank U very much for Ur job!

**Comment by remittor** [comment]
Fixed
